//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;

namespace screenerWpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecordsSavePath {
            get
            {
                if (string.IsNullOrEmpty((string)this["RecordsSavePath"]))
                {
                    string defaultPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyVideos));
                    this["RecordsSavePath"] = defaultPath;
            }
                return (string)this["RecordsSavePath"];
            }
            set {
                this["RecordsSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScreenshotsSavePath {
            get
            {
                if (string.IsNullOrEmpty((string)this["ScreenshotsSavePath"]))
                {
                    string defaultPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyPictures));
                    this["ScreenshotsSavePath"] = defaultPath;
                }
                return (string)this["ScreenshotsSavePath"];
            }
            set {
                this["ScreenshotsSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScreenshotsLibrary {
            get
            {
                if (string.IsNullOrEmpty((string)this["ScreenshotsLibrary"]))
                {
                    string defaultPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyPictures));
                    this["ScreenshotsLibrary"] = defaultPath;
                }
                return (string)this["ScreenshotsLibrary"];
            }
            set {
                this["ScreenshotsLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DropboxAppKey {
            get {
                return ((string)(this["DropboxAppKey"]));
            }
            set {
                this["DropboxAppKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DropboxAppSecret {
            get {
                return ((string)(this["DropboxAppSecret"]));
            }
            set {
                this["DropboxAppSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveScreenshots
        {
            get
            {
                return ((bool)(this["AutoSaveScreenshots"]));
            }
            set {
                this["AutoSaveScreenshots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial")]
        public string DefaultFontFamily {
            get {
                return ((string)(this["DefaultFontFamily"]));
            }
            set {
                this["DefaultFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int DefaultFontSize
        {
            get
            {
                return ((int)(this["DefaultFontSize"]));
            }
            set {
                this["DefaultFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DefaultThickness
        {
            get
            {
                return ((int)(this["DefaultThickness"]));
            }
            set {
                this["DefaultThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DefaultTransparency
        {
            get
            {
                return ((int)(this["DefaultTransparency"]));
            }
            set {
                this["DefaultTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string DefaultColor {
            get {
                return ((string)(this["DefaultColor"]));
            }
            set {
                this["DefaultColor"] = value;
            }
        }
    }
}
